"""The dungeons a player can record in, and the ones a mislabelled dive can be caught in.

GENERATED by tools/build_dungeons.py — do not edit by hand.

WHY IN CODE
-----------
It is an id and a name per language. Carried as a file, the client could not start without
one: the picker is populated from it, and an empty picker blocks recording entirely, so a
file built from the game's own assets would become a hard dependency of a program that
otherwise only reads the screen.

TWO LISTS, TWO JOBS
-------------------
`DUNGEONS` is every dungeon, and it is what the picker offers. `STUDY_IDS` is the subset
whose junk carries the dungeon's own name — the ones where the client can cross-check a
player's choice against what fell out of the chest. The picker used to offer only those,
which meant a player farming anywhere else could not say where they were; a dive recorded
without a cross-check is worth more than a dive that could not be recorded.

A `catalog.<locale>.json` beside the client still overrides the whole table, for a fuller or
newer list without a new build.
"""
from __future__ import annotations


# id -> the name the game shows, per interface language.
DUNGEONS: dict[int, dict[str, str]] = {
    2000: {"zh_tw": "初始的奈落", "zh_cn": "初始的奈落", "ja": "はじまりの奈落", "ko": "시작의 나락", "en": "Beginning Abyss", "de": "Beginn des Abyss"},
    2001: {"zh_tw": "貿易水路", "zh_cn": "贸易水路", "ja": "交易水路", "ko": "교역 수로", "en": "Trade Waterway", "de": "Handelskanal"},
    2002: {"zh_tw": "不落的要塞", "zh_cn": "不落的要塞", "ja": "不落の城塞", "ko": "난공불락의 성채", "en": "Impregnable Fortress", "de": "Uneinnehm. Festung"},
    2003: {"zh_tw": "豪雪地帶", "zh_cn": "豪雪地带", "ja": "豪雪地帯", "ko": "대설 지대", "en": "Deepsnow Hinterlands", "de": "Schneegebiet"},
    3000: {"zh_tw": "草原", "zh_cn": "草原", "ja": "草原", "ko": "초원", "en": "Grasslands", "de": "Grasland"},
    4000: {"zh_tw": "火之魔窟", "zh_cn": "火之魔窟", "ja": "火の魔窟", "ko": "불의 마굴", "en": "Den of Fire", "de": "Feuerschlund"},
    4001: {"zh_tw": "風之魔窟", "zh_cn": "风之魔窟", "ja": "風の魔窟", "ko": "바람의 마굴", "en": "Den of Wind", "de": "Sturmschlund"},
    4002: {"zh_tw": "光之魔窟", "zh_cn": "光之魔窟", "ja": "光の魔窟", "ko": "빛의 마굴", "en": "Den of Light", "de": "Lichtschlund"},
    4003: {"zh_tw": "土之魔窟", "zh_cn": "土之魔窟", "ja": "土の魔窟", "ko": "땅의 마굴", "en": "Den of Earth", "de": "Erdschlund"},
    4005: {"zh_tw": "水之魔窟", "zh_cn": "水之魔窟", "ja": "水の魔窟", "ko": "물의 마굴", "en": "Den of Water", "de": "Wasserschlund"},
    5000: {"zh_tw": "西部的洞窟", "zh_cn": "西部的洞窟", "ja": "西の洞窟", "ko": "서쪽 동굴", "en": "Western Cave", "de": "Westliche Höhle"},
    5001: {"zh_tw": "被詛咒的洞窟", "zh_cn": "被诅咒的洞窟", "ja": "呪われし洞窟", "ko": "저주받은 동굴", "en": "Cursed Cave", "de": "Verfluchte Höhle"},
    5002: {"zh_tw": "南部的洞窟", "zh_cn": "南部的洞窟", "ja": "南の洞窟", "ko": "남쪽의 동굴", "en": "Southern Cave", "de": "Südliche Höhle"},
    5003: {"zh_tw": "避雨的的洞窟", "zh_cn": "避雨的的洞窟", "ja": "雨除けの洞窟", "ko": "비를 피하는 동굴", "en": "Rain Shelter Cave", "de": "Zufluchtshöhle vor dem Regen"},
    5004: {"zh_tw": "惡魔所居之山", "zh_cn": "恶魔所居之山", "ja": "悪魔の住まう山", "ko": "악마가 머무는 산", "en": "Mountain Where the Devil Dwells", "de": "Dämonenberg"},
    5005: {"zh_tw": "村外的地下洞穴", "zh_cn": "村外的地下洞穴", "ja": "村はずれの地下洞窟", "ko": "마을 외곽의 지하 동굴", "en": "Underground Cave at the Edge of the Village", "de": "Unterirdische Höhle am Dorfrand"},
    5006: {"zh_tw": "千年鄉", "zh_cn": "千年乡", "ja": "千年郷", "ko": "천년향", "en": "The Millennial Lands", "de": "Das Jahrtausendreich"},
    5007: {"zh_tw": "亡靈島", "zh_cn": "亡灵岛", "ja": "亡霊島", "ko": "망령섬", "en": "Island of Ghosts", "de": "Geisterinsel"},
    5008: {"zh_tw": "盧・比肯的洞窟", "zh_cn": "卢・比肯的洞窟", "ja": "ル・ビッケンの洞窟", "ko": "루 비켄의 동굴", "en": "Le Bicken Cave", "de": "Le-Biquen-Höhle"},
    5009: {"zh_tw": "矮人洞窟", "zh_cn": "矮人洞窟", "ja": "ドワーフの洞窟", "ko": "드워프의 동굴", "en": "Dwarves' Cave", "de": "Zwergenhöhle"},
    5010: {"zh_tw": "古舊王墓", "zh_cn": "古旧王墓", "ja": "旧き王墓", "ko": "옛 왕의 묘", "en": "Old Royal Sepulcher", "de": "Altes Königsgrab"},
    5011: {"zh_tw": "別離洞窟", "zh_cn": "别离洞窟", "ja": "別離の洞窟", "ko": "영별의 동굴", "en": "Cave of Separation", "de": "Höhle des Abschieds"},
    5012: {"zh_tw": "魔女洞窟", "zh_cn": "魔女洞窟", "ja": "魔女の洞窟", "ko": "마녀의 동굴", "en": "The Witch's Cave", "de": "Höhle der Hexe"},
    5013: {"zh_tw": "藥師神殿", "zh_cn": "药师神殿", "ja": "薬師の祠", "ko": "약사의 사당", "en": "Herbalist's Shrine", "de": "Schrein der Heilkundingen"},
    5014: {"zh_tw": "王之試煉", "zh_cn": "王之试炼", "ja": "王の試練", "ko": "왕의 시련", "en": "King's Trial", "de": "Königsprüfungen"},
    5016: {"zh_tw": "百花之庭", "zh_cn": "百花之庭", "ja": "百花の庭", "ko": "백화의 정원", "en": "Garden of the Hundredfold Blossom", "de": "Garten des Blütenmeers"},
    5017: {"zh_tw": "亞歌拉神殿", "zh_cn": "亚歌拉神殿", "ja": "アゴラの神殿", "ko": "아고라의 신전", "en": "Shrine of Agora", "de": "Agoras Tempel"},
    5018: {"zh_tw": "雷鳴洞窟", "zh_cn": "雷鸣洞窟", "ja": "雷鳴の洞窟", "ko": "천둥의 동굴", "en": "Cave of Thunder", "de": "Höhle des Donners"},
    5019: {"zh_tw": "前奧溫領地寺院", "zh_cn": "前奥温领地寺院", "ja": "旧オーウェン領寺院", "ko": "옛 오웬령 사원", "en": "Temple of the Old Owen Lands", "de": "Kloster im ehemaligen Herrschaftsgebiet von Owen"},
    5020: {"zh_tw": "哥布林的住處", "zh_cn": "哥布林的住处", "ja": "ゴブリンの住処", "ko": "고블린 주거지", "en": "Goblin's Abode", "de": "Goblinlager"},
    5400: {"zh_tw": "試煉洞窟", "zh_cn": "试炼洞窟", "ja": "試練の洞窟", "ko": "시련의 동굴", "en": "Cave of Trials", "de": "Höhle der Prüfungen"},
    5401: {"zh_tw": "試煉洞窟（青銅階）", "zh_cn": "试炼洞窟（青铜阶）", "ja": "試練の洞窟（青銅等級）", "ko": "시련의 동굴 (청동 등급)", "en": "Cave of Trials (Bronze Grade)", "de": "Höhle der Prüfungen (Bronzerang)"},
    5402: {"zh_tw": "試煉洞窟（鐵階）", "zh_cn": "试炼洞窟（铁阶）", "ja": "試練の洞窟（鉄等級）", "ko": "시련의 동굴 (철 등급)", "en": "Cave of Trials (Iron Grade)", "de": "Höhle der Prüfungen (Eisenrang)"},
    5403: {"zh_tw": "試煉洞窟（鋼階）", "zh_cn": "试炼洞窟（钢阶）", "ja": "試練の洞窟（鋼等級）", "ko": "시련의 동굴 (강철 등급)", "en": "Cave of Trials (Steel Grade)", "de": "Höhle der Prüfungen (Stahlrang)"},
    5404: {"zh_tw": "試煉洞窟（銅階）", "zh_cn": "试炼洞窟（铜阶）", "ja": "試練の洞窟（銅等級）", "ko": "시련의 동굴 (구리 등급)", "en": "Cave of Trials (Copper Grade)", "de": "Höhle der Prüfungen (Kupferrang)"},
    5500: {"zh_tw": "戰士靈廟", "zh_cn": "战士灵庙", "ja": "戦士の霊廟", "ko": "전사의 영묘", "en": "Fighter Tomb", "de": "Grabmal des Kriegers"},
    6000: {"zh_tw": "古城遺跡", "zh_cn": "古城遗迹", "ja": "古城跡", "ko": "고성터", "en": "Old Castle Ruins", "de": "Burgruine"},
    6500: {"zh_tw": "英雄戰域", "zh_cn": "英雄战域", "ja": "英雄の戦域", "ko": "영웅의 전장", "en": "Battlefront of Heroes", "de": "Schlachtfeld der Helden"},
    7000: {"zh_tw": "怨嗟洞窟", "zh_cn": "怨嗟洞窟", "ja": "怨嗟の洞窟", "ko": "원한의 동굴", "en": "Cave of Malice", "de": "Höhle des Grolls"},
    7001: {"zh_tw": "花之洞窟", "zh_cn": "花之洞窟", "ja": "花の洞窟", "ko": "꽃의 동굴", "en": "Cave of Flowers", "de": "Höhle der Blumen"},
    7002: {"zh_tw": "弗德萊戈的迷宮", "zh_cn": "弗德莱戈的迷宫", "ja": "フォードレイグの迷宮", "ko": "포드레이그의 미궁", "en": "Labyrinth of Fordraig", "de": "Fordraigs Labyrinth"},
    7004: {"zh_tw": "沙華魚人洞窟", "zh_cn": "沙华鱼人洞窟", "ja": "サハギンの洞窟", "ko": "사하긴의 동굴", "en": "Sahuagin's Cave", "de": "Sahagin-Grotte"},
    7005: {"zh_tw": "戰士的試煉", "zh_cn": "战士的试炼", "ja": "戦士の試練", "ko": "전사의 시련", "en": "Fighter Trials", "de": "Kriegerprüfung"},
    7006: {"zh_tw": "砂影洞窟", "zh_cn": "砂影洞窟", "ja": "砂影の洞窟", "ko": "모래 그림자의 동굴", "en": "Sand Shadow Cave", "de": "Höhle des Dünenschattens"},
    7007: {"zh_tw": "陽炎試煉", "zh_cn": "阳炎试炼", "ja": "陽炎の試練", "ko": "아지랑이의 시련", "en": "Trial of the Heat-Haze", "de": "Prüfung der Hitzeschleier"},
    7008: {"zh_tw": "拂曉之路", "zh_cn": "拂晓之路", "ja": "夜明けの往路", "ko": "새벽의 여정", "en": "Outward Path to Daybreak", "de": "Pfad der Morgenröte"},
    7009: {"zh_tw": "白堊狼穴", "zh_cn": "白垩狼穴", "ja": "白亜の狼穴", "ko": "백아의 동굴", "en": "Alabaster Wolf Den", "de": "Kreideweiße Wolfshöhle"},
    7010: {"zh_tw": "鬼啼島", "zh_cn": "鬼啼岛", "ja": "鬼啼島", "ko": "귀곡도", "en": "Island of the Wailing Oni", "de": "Insel des klagenden Oni"},
    7011: {"zh_tw": "巖心流道場", "zh_cn": "岩心流道场", "ja": "巌心流道場", "ko": "암심류 도장", "en": "Rock-Heart Style Dojo", "de": "Dojo des standhaften Herzens"},
    7014: {"zh_tw": "藥種古蹟", "zh_cn": "药种古迹", "ja": "薬種の古跡", "ko": "고대 약초 유적", "en": "Ancient Grounds of Materia Medica", "de": "Alte Heilstätte"},
    7015: {"zh_tw": "北穿幽靈城", "zh_cn": "北穿幽灵城", "ja": "北穿の幽霊城", "ko": "북쪽의 유령성", "en": "Ghost Castle of the Northcleft", "de": "Geisterschloss der Nordbresche"},
    7016: {"zh_tw": "紫繭洞窟", "zh_cn": "紫茧洞窟", "ja": "紫繭の洞窟", "ko": "자색 고치의 동굴", "en": "Purple Cocoon Cave", "de": "Purpurseidenhöhle"},
    7500: {"zh_tw": "法師的試煉", "zh_cn": "法师的试炼", "ja": "魔術師の試練", "ko": "마법사의 시련", "en": "Mage Trials", "de": "Magierprüfung"},
    7501: {"zh_tw": "騎士的試煉", "zh_cn": "骑士的试炼", "ja": "騎士の試練", "ko": "기사의 시련", "en": "Knight Trials", "de": "Ritterprüfung"},
    7502: {"zh_tw": "盜賊的試煉", "zh_cn": "盗贼的试炼", "ja": "盗賊の試練", "ko": "도적의 시련", "en": "Thief Trials", "de": "Diebesprüfung"},
}


# The dungeons whose junk carries the dungeon's own name, so a mislabelled dive
# can be caught. A claim about the ITEMS, not about the table above.
STUDY_IDS: tuple[int, ...] = (2000, 2001, 2003, 4000, 4001, 4002, 4003, 4005, 5014, 5016, 5018, 6000, 7000, 7001, 7006, 7008, 7010, 7014, 7015)


def name(dungeon_id: int, locale: str = "") -> str:
    """What to call a dungeon in the window's language.

    Falls back to another language rather than to an id: a number is not a place,
    and a player choosing where they are cannot use one.
    """
    names = DUNGEONS.get(int(dungeon_id)) or {}
    return names.get(locale) or names.get("zh_tw") or next(iter(names.values()), "")


def catalog(locale: str = "") -> list[dict]:
    """The same shape a `catalog.<locale>.json` would give, minus the floors.

    No floors on purpose. The floor control is hidden and every record files a null
    floor — a player will not keep a floor dropdown current through a dive, and a
    stale floor is worse than an honest null in the one field the analysis strata
    are built on.
    """
    return [{"id": key, "name": name(key, locale), "floors": []}
            for key in sorted(DUNGEONS)]


# Kept for the cross-check, which wants id -> name in one language.
STUDY_DUNGEONS: dict[int, str] = {key: name(key) for key in STUDY_IDS}
