"""Is there a newer client than this one?

WHY THIS EXISTS BESIDE THE SERVER'S FLOOR, RATHER THAN INSTEAD OF IT
--------------------------------------------------------------------
The ingest server refuses builds below a floor, which is the enforcement — but it only ever
reaches a player who UPLOADS. Sharing is off until asked and asked only once, so a player who
never turned it on, or who has not uploaded yet, is never told anything at all. They can farm
for a week on a build known to mis-read the mining panel and nothing on their screen says so.

That is the gap this closes, and it is the whole job: TELL them, and link. It does not
download, verify or replace anything. Swapping a running exe on Windows means SmartScreen
reputation on an unsigned 65MB binary, antivirus, and a rename-swap dance — a project, not a
feature, and one to start from code signing rather than from here.

WHERE THE ANSWER COMES FROM, AND WHY NOT A FILE WE WRITE
--------------------------------------------------------
GitHub's own releases API, which already publishes exactly what a hand-written `latest.json`
would have carried — tag, asset name, size, sha256 digest, download URL — generated by the
release itself:

    GET https://api.github.com/repos/<owner>/<repo>/releases/latest

A JSON committed beside the client would be a SECOND copy of that truth, kept in step by
someone remembering to. This project has now paid for that mistake twice in one day: a
workflow holding its own copy of the build's dependency list (the exe shipped without two
capabilities), and a release tag able to disagree with CLIENT_VERSION. The version that
cannot drift is the one nobody maintains.

WHAT LEAVES THE MACHINE
-----------------------
One unauthenticated GET to api.github.com, carrying what any HTTP request carries: an IP and
a user agent. No install_id, no records, nothing about the game. It is still a THIRD PARTY
this client otherwise never speaks to, so it is disclosed in DISCLAIMER.md and switchable in
Settings — a study that asks permission before collecting anything should not quietly acquire
a new correspondent.

IT NEVER MATTERS ENOUGH TO FAIL
-------------------------------
Offline, rate-limited, GitHub down, a shape that has changed since this was written: every
one of those is `None` and silence. Nothing here may delay the window, and nothing here may
touch capture — a player mid-session is doing the one thing this program exists for.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass

from wddrop_schema.versioning import is_newer

from .config import CLIENT_VERSION

log = logging.getLogger("wddrop.updates")

# The client's own home. Named here rather than configured: a setting for "where do updates
# come from" is a setting for "who may tell this program to fetch a binary".
REPO = "exkuretrol/wddrop-client"
LATEST_URL = f"https://api.github.com/repos/{REPO}/releases/latest"
RELEASES_PAGE = f"https://github.com/{REPO}/releases/latest"
# Short. This runs while the player is waiting to press Start, and the answer is never worth
# waiting for — it is worth having by the time they look at it.
TIMEOUT_SECONDS = 5.0


@dataclass(frozen=True)
class Update:
    """A release newer than this build. `page` is where a player goes to get it."""

    version: str
    page: str
    # Published by GitHub, carried because it costs nothing to carry. Nothing verifies it
    # today — the client does not download the file — and it is here so that whoever adds
    # that later does not have to change this layer to get it.
    sha256: str | None = None
    size_bytes: int | None = None


def latest(url: str = LATEST_URL, timeout: float = TIMEOUT_SECONDS) -> Update | None:
    """Ask GitHub what the newest release is. None for every kind of no-answer."""
    import httpx

    try:
        response = httpx.get(
            url,
            timeout=timeout,
            headers={
                # GitHub asks for a real one and answers 403 without it. Naming the client
                # and its version also means a look at their logs says which builds are
                # still out there, which is the same question the floor is about.
                "User-Agent": f"wddrop/{CLIENT_VERSION}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        response.raise_for_status()
        body = response.json()
    except Exception as exc:                                # noqa: BLE001
        log.debug("wddrop: no answer about updates: %s", exc)
        return None

    if not isinstance(body, dict):
        # Valid JSON of the wrong shape — a rate-limit note, an error document, a list.
        # Guarded because it lands OUTSIDE the request's own try: the promise this function
        # makes is None for every kind of no-answer, and "the reply parsed but meant
        # something else" is one of those.
        log.debug("wddrop: the release answer was %s, not an object", type(body).__name__)
        return None

    tag = body.get("tag_name") or body.get("name")
    if not tag or body.get("draft") or body.get("prerelease"):
        # A draft is not released and a pre-release is not for everyone. Either would send
        # players after a build we did not mean them to have.
        return None
    asset = next((a for a in body.get("assets") or [] if str(a.get("name", "")).endswith(".exe")),
                 None)
    digest = (asset or {}).get("digest") or ""
    return Update(
        version=str(tag).lstrip("vV"),
        page=body.get("html_url") or RELEASES_PAGE,
        sha256=digest.split("sha256:")[-1] if "sha256:" in digest else None,
        size_bytes=(asset or {}).get("size"),
    )


def look(cfg, *, running: str = CLIENT_VERSION) -> tuple[str, Update | None]:
    """Ask, and say WHICH of the three answers came back.

    `"newer"`, `"current"`, `"unreachable"`. The launch check folds the last two together
    because it has nothing to say about either — but a player who PRESSED a button has, and
    "you are up to date" and "GitHub did not answer" are not the same news. A button that
    stays silent on failure is indistinguishable from a button that does nothing.

    The setting is consulted HERE rather than at the call site, so that turning it off turns
    off the request itself and not merely the message about it. A switch that still makes
    the call is not the switch the player was offered.
    """
    if not getattr(cfg, "check_updates", True):
        return "unreachable", None
    found = latest()
    if found is None:
        return "unreachable", None
    if not is_newer(found.version, running):
        log.info("wddrop: %s is the newest release and this is %s", found.version, running)
        return "current", found
    log.info("wddrop: %s is available (this is %s)", found.version, running)
    return "newer", found


def check(cfg, *, running: str = CLIENT_VERSION) -> Update | None:
    """Is there something newer, and may we ask? None for both kinds of no."""
    state, found = look(cfg, running=running)
    return found if state == "newer" else None
